name: best_way_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  get_it: ^7.6.7
  http: ^1.2.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_test:
    sdk: flutter
  freezed: ^2.3.4
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
